version: '3'

services:
  redis:
    container_name: telequiz_redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  postgres:
    container_name: telequiz_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DB: telequizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
#   volumes:
#     - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
